on:
  pull_request:
    types: [closed]
    
jobs:
  cherrypick:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
       - run: echo ${{fromJSON(github.event)}}
#      - uses: actions/github-script@v6
#        with:
#          github-token: ${{ secrets.PAT }}
#          script: |
#            github.rest.repos.setAdminBranchProtection({
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              branch: 'main',
#            });
