on:
  pull_request:
    types: [closed]
    
jobs:
  cherrypick:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
#      - run: echo ${{ toJSON(github.event.pull_request.base.ref) }}
#      - run: echo ${{ toJSON(github.event) }}
      - uses: actions/github-script@v6
        with:
          # github-token: ${{ secrets.TOKEN }}
          script: |
            console.log(context);
            
#            const PR = octokit.rest.pulls.get({
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              pull_number,
#            });

