on:
  pull_request:
    types: [closed]
    
jobs:
  cherrypick:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          # github-token: ${{ secrets.TOKEN }}
          script: |            
            // get the details for the PR
            const PR = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.number
            });
            
            // read all branches 
            const BRANCHES = await github.rest.repos.listBranches({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            
            console.log(BRANCHES);
            
            // search for hotfix branch name

            if (PR.data.labels?.includes('hotfix')) {
            // hotfix label is active
            //
            }
            
            
  #            data: [
  #  { name: 'hotfix/v2.5.x', commit: [Object], protected: false },
  #  { name: 'hotfix/v3.1.x', commit: [Object], protected: false },
  #  { name: 'konne-patch-4', commit: [Object], protected: false },
  #  { name: 'main', commit: [Object], protected: false }
  # ]
